### ISSUE TITLE
beter maken

### ISSUE THREAD

**Issue by arnevandoorslaer** [LiamThys/liamthys.github.io#2]
ik zou het gewoon beter maken eigenlijk, eventueel meer code ofzo

**Comment by lem-onade** [comment]
er ontbreekt wat code in je <body>

**Comment by lem-onade** [comment]
volgens mij ontbreekt er wat in je

**Comment by lem-onade** [comment]
in je

**Comment by lem-onade** [comment]
body van de pagina

**Comment by lem-onade** [comment]
reopen pls
